# Generated by Django 3.0.2 on 2021-06-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cart_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Not Paid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(default='Not Shipped', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
